# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/timurnogaev/unix-shell-and-utils-TimurN4/OOP_3Laba

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/timurnogaev/unix-shell-and-utils-TimurN4/OOP_3Laba

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timurnogaev/unix-shell-and-utils-TimurN4/OOP_3Laba/CMakeFiles /home/timurnogaev/unix-shell-and-utils-TimurN4/OOP_3Laba//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timurnogaev/unix-shell-and-utils-TimurN4/OOP_3Laba/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GeometryProject

# Build rule for target.
GeometryProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GeometryProject
.PHONY : GeometryProject

# fast build rule for target.
GeometryProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/build
.PHONY : GeometryProject/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/main.cpp.s
.PHONY : main.cpp.s

src/point.o: src/point.cpp.o
.PHONY : src/point.o

# target to build an object file
src/point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/point.cpp.o
.PHONY : src/point.cpp.o

src/point.i: src/point.cpp.i
.PHONY : src/point.i

# target to preprocess a source file
src/point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/point.cpp.i
.PHONY : src/point.cpp.i

src/point.s: src/point.cpp.s
.PHONY : src/point.s

# target to generate assembly for a file
src/point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/point.cpp.s
.PHONY : src/point.cpp.s

src/rectangle.o: src/rectangle.cpp.o
.PHONY : src/rectangle.o

# target to build an object file
src/rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/rectangle.cpp.o
.PHONY : src/rectangle.cpp.o

src/rectangle.i: src/rectangle.cpp.i
.PHONY : src/rectangle.i

# target to preprocess a source file
src/rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/rectangle.cpp.i
.PHONY : src/rectangle.cpp.i

src/rectangle.s: src/rectangle.cpp.s
.PHONY : src/rectangle.s

# target to generate assembly for a file
src/rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/rectangle.cpp.s
.PHONY : src/rectangle.cpp.s

src/square.o: src/square.cpp.o
.PHONY : src/square.o

# target to build an object file
src/square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/square.cpp.o
.PHONY : src/square.cpp.o

src/square.i: src/square.cpp.i
.PHONY : src/square.i

# target to preprocess a source file
src/square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/square.cpp.i
.PHONY : src/square.cpp.i

src/square.s: src/square.cpp.s
.PHONY : src/square.s

# target to generate assembly for a file
src/square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/square.cpp.s
.PHONY : src/square.cpp.s

src/triangle.o: src/triangle.cpp.o
.PHONY : src/triangle.o

# target to build an object file
src/triangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/triangle.cpp.o
.PHONY : src/triangle.cpp.o

src/triangle.i: src/triangle.cpp.i
.PHONY : src/triangle.i

# target to preprocess a source file
src/triangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/triangle.cpp.i
.PHONY : src/triangle.cpp.i

src/triangle.s: src/triangle.cpp.s
.PHONY : src/triangle.s

# target to generate assembly for a file
src/triangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeometryProject.dir/build.make CMakeFiles/GeometryProject.dir/src/triangle.cpp.s
.PHONY : src/triangle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GeometryProject"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/point.o"
	@echo "... src/point.i"
	@echo "... src/point.s"
	@echo "... src/rectangle.o"
	@echo "... src/rectangle.i"
	@echo "... src/rectangle.s"
	@echo "... src/square.o"
	@echo "... src/square.i"
	@echo "... src/square.s"
	@echo "... src/triangle.o"
	@echo "... src/triangle.i"
	@echo "... src/triangle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

